# 1. NAMA ROBOT (Workflow)
name: Continuous Integration Otomatis Web App

# 2. KAPAN ROBOT BEKERJA (Trigger)
on:
  push:
    branches: [ "main", "master" ] # Bekerja saat ada push ke main atau master
  pull_request:
    branches: [ "main", "master" ] # Bekerja saat ada Pull Request

# 3. PEKERJAAN ROBOT (Jobs)
jobs:
  build_dan_test:
    runs-on: ubuntu-latest

    steps:
    - name: Ambil Kode dari Gudang
      uses: actions/checkout@v4

    - name: Siapkan Lingkungan PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Pasang Alat (Dependensi) Proyek
      run: composer install --prefer-dist --no-progress

    - name: Cek Syntax dan Kualitas Kode PHP
      run: vendor/bin/phpcs app/ tests/

    - name: Pekerjaan Selesai
      run: echo "Pemeriksaan Kode Berhasil! Siap untuk dipublikasikan."
